'use strict';

const GameStatus = Object.freeze({
  SHOW_ROOM: 'SHOW_ROOM',
  SHOW_START: 'SHOW_START',
  SHOW_PREPARED: 'SHOW_PREPARED',
  SHOW_QUESTION: 'SHOW_QUESTION',
  SELECT_ANSWER: 'SELECT_ANSWER',
  SHOW_RESPONSES: 'SHOW_RESPONSES',
  SHOW_LEADERBOARD: 'SHOW_LEADERBOARD',
  FINISHED: 'FINISHED',
});

module.exports = GameStatus;
